INSERT INTO `bookstore`.`category` (`id`, `name`) VALUES ('1', 'Tư duy - kỹ năng sống');
INSERT INTO `bookstore`.`category` (`id`, `name`) VALUES ('2', 'Kiến thức - Bách khoa');
INSERT INTO `bookstore`.`category` (`id`, `name`) VALUES ('3', 'Tiểu thuyết');

INSERT INTO `bookstore`.`product` (`id`, `idCategory`, `name`, `image`, `originalPrice`, `salePrice`, `discription`, `quantity`, `active`) VALUES ('1', '1', 'Tâm Lý Học Hành Vi', 'https://salt.tikicdn.com/cache/w1200/ts/product/cd/72/24/a9f929f98397d1be047e47602989a5e0.jpg', '67500', '81500', 'Tâm Lý Học Hành Vi.Cuốn sách giúp bạn thấu hiểu bản thân mình và tâm lý những người xung quanh!Được chấp bút bởi bậc thầy tâm lý hàng đầu Trung Quốc Khương Nguy.', '50', 1);
INSERT INTO `bookstore`.`product` (`id`, `idCategory`, `name`, `image`, `originalPrice`, `salePrice`, `discription`, `quantity`, `active`) VALUES ('2', '1', 'Người trong muôn nghề', 'https://salt.tikicdn.com/cache/w1200/ts/product/07/3e/ae/26cc99e58483d0030de5e8dc777e3d81.jpg', '155000', '169000', 'Chọn nghề là giúp mình tìm được điểm giao thoa giữa năng lực, sở thích cá nhân với nhu cầu của xã hội.Người Trong Muôn Nghề hi vọng có thể kéo bạn lại gần hơn với mục đích bản chất ấy. Cuốn sách là tuyển tập những câu chuyện đi làm tâm huyết đến từ những cây viết dày dặn kinh nghiệm trong các lĩnh vực chuyên môn và những môi trường làm việc khác nhau. Những chia sẻ này sẽ giúp các bạn học sinh, sinh viên có một cái nhìn toàn diện hơn về thế giới công việc thực thụ', '100', 1);
INSERT INTO `bookstore`.`product` (`id`, `idCategory`, `name`, `image`, `originalPrice`, `salePrice`, `discription`, `quantity`, `active`) VALUES ('3', '2', 'Luật Tâm Thức - Giải Mã Ma Trận Vũ Trụ', 'https://salt.tikicdn.com/cache/w1200/ts/product/4f/b0/bf/dbff1a3a306b9adc591620553ce99a9d.jpg', '220000', '227000', 'Cuốn sách này sẽ giúp bạn thấy rằng những kiến thức của người xưa không hề cao siêu huyền bí mà vô cùng đơn giản và liên quan chặt chẽ tới khoa học hiện đại.Việc của bạn chỉ là đọc với một tâm trí cởi mở để thức tỉnh, vượt qua những rào cản của tâm trí, những niềm tin cố hữu của mình', '150', b'1');
INSERT INTO `bookstore`.`product` (`id`, `idCategory`, `name`, `image`, `originalPrice`, `salePrice`, `discription`, `quantity`, `active`) VALUES ('4', '2', 'Nhập môn Triết học', 'https://salt.tikicdn.com/cache/w1200/ts/product/31/1f/d7/fbf6adcd3880d84b851c02e4b2324f8a.png', '90000', '97500', 'NHẬP MÔN TRIẾT HỌC QUA 101 C U ĐỐ KINH ĐIỂN, ấn bản thứ tư của Martin Cohen giới thiệu triết học theo cách giải trí nhưng bổ ích và kích thích tư duy. Sử dụng các câu đố hóc búa và nghịch lý, ông đã khéo léo mở ra một số bí ẩn của chủ đề này, từ những gì chúng ta biết – hoặc nghĩ rằng chúng ta biết – cho đến những thí nghiệm tư duy “xoắn não” về đạo đức, khoa học và bản chất của tâm trí', '98', 1);
INSERT INTO `bookstore`.`product` (`id`, `idCategory`, `name`, `image`, `originalPrice`, `salePrice`, `discription`, `quantity`, `active`) VALUES ('5', '3', 'Mặt Nạ - Tiểu Thuyết', 'https://salt.tikicdn.com/cache/w1200/ts/product/79/cb/7f/219f98e7f609290fd8a513fa25c41b17.jpg', '70000', '77500', 'Họ có thực sự hạnh phúc với hình tượng mình gây dựng bao lâu nay trong mắt mọi người? Mỗi buổi sáng thức dậy, đứng trước gương họ thầm nhủ hôm nay mình sẽ diễn vai gì? Một cô gái cá tính hay thục nữ yêu kiều? Một chàng trai phong trần hay quân tử hảo hán? Mọi hỷ - nộ - ái - ố trong lòng, bạn có thực sự muốn chia sẻ với người khác?', '80', 1);
INSERT INTO `bookstore`.`user` (`name`, `address`, `email`, `phone`, `password`,`isRole`, `active`) 
	VALUES ('Ngọc Anh', 'Đống Đa, Hà Nội', 'ngocanh@gmail.com', '0365894523', '0235256124','3', default);
    
INSERT INTO `bookstore`.`user` (`name`, `address`, `email`, `phone`, `password`,`isRole`, `active`) 
	VALUES ('Võ Lâm', 'Đà Nẵng', 'lamvo@gmail.com', '0875325142', '12345678','2', default);
    
INSERT INTO `bookstore`.`user` (`name`, `address`, `email`, `phone`, `password`,`isRole`, `active`) 
VALUES ('Trúc Anh', 'TP.HCM', 'trucanh@gmail.com', '0321525478', '12345678','1', default);

